### ISSUE TITLE
Wizzard crash

### ISSUE THREAD

**Issue by MarvinKlein1508** [Jurioli/Blazor.WebForm.Components#1]
I'm opening the wizzard page from your demo app and I get this exception:

https://blazorwebformdemo.github.io/Standard/Wizard/
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Unable to set property 'FontSize' on object of type 'asp.Wizard'. The error was: The numeric part ('0.8') of '0.8em' cannot be parsed as a numeric part of a Em unit.
System.InvalidOperationException: Unable to set property 'FontSize' on object of type 'asp.Wizard'. The error was: The numeric part ('0.8') of '0.8em' cannot be parsed as a numeric part of a Em unit.
 ---> System.FormatException: The numeric part ('0.8') of '0.8em' cannot be parsed as a numeric part of a Em unit.
   at System.Web.UI.WebControls.Unit..ctor(String value, CultureInfo culture, UnitType defaultType)
   at System.Web.UI.WebControls.FontUnit..ctor(String value, CultureInfo culture)
   at System.Web.UI.WebControls.FontUnit.Parse(String s, CultureInfo culture)
   at System.Web.UI.WebControls.FontUnitConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.TypeConverter.ConvertFromString(ITypeDescriptorContext , CultureInfo , String )
   at Blazor.WebForm.UI.ControlParameterViewComponentExtensions.ConvertFromString[FontUnit](IParameterViewComponent component, String value)
   at Blazor.WebForm.UI.ControlComponents.WebControlComponent`1[[System.Web.UI.WebControls.Wizard, Blazor.WebForm.UI, Version=2.3.0.3, Culture=neutral, PublicKeyToken=fe1bd156e56b2897]].set_FontSize(String value)
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[Wizard,String](Action`2 setter, Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.SetValue(Object , Object )
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object , PropertySetter , String , Object )
   Exception_EndOfInnerExceptionStack
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object , PropertySetter , String , Object )
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& , Object )
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object )
   at System.Web.UI.ControlComponent`1[[System.Web.UI.WebControls.Wizard, Blazor.WebForm.UI, Version=2.3.0.3, Culture=neutral, PublicKeyToken=fe1bd156e56b2897]].SetParametersAsync(ParameterView parameters)
   at Blazor.WebForm.UI.ControlComponents.ControlComponentBase`1[[System.Web.UI.WebControls.Wizard, Blazor.WebForm.UI, Version=2.3.0.3, Culture=neutral, PublicKeyToken=fe1bd156e56b2897]].SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView )
```

My browser locale is de-DE

**Comment by Jurioli** [comment]
Thank you for your report! I fixed this issue on [2.3.0.4](https://github.com/Jurioli/Blazor.WebForm.Components/commit/1309cce2f139fe27e451148c02e890678bb79681).
